package videorentalsoftware;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dhruv
 */


public class ManagerForm extends javax.swing.JFrame {

    /**
     * Creates new form ManagerForm
     */
    public ManagerForm() {
        initComponents();
    }

    public String quotate(String s) {
        return "'" + s + "'";
    }

    public int getItemId(int id) {
        int rent = 0;

        try {
            Connection conn = new ConnectionHandler().createConnection();
            Statement st = conn.createStatement();

            String query = "select * from Sales where id = " + id;

            ResultSet rs = st.executeQuery(query);

            if (rs.next()) {
                rent = rs.getInt("itemId");
            }
            return rent;

        } catch (SQLException ex) {
            Logger.getLogger(ClerkForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(ClerkForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ClerkForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 0;
    }

    public int getCustId(int id) {
        int rent = 0;

        try {
            Connection conn = new ConnectionHandler().createConnection();
            Statement st = conn.createStatement();

            String query = "select * from Sales where id = " + id;

            ResultSet rs = st.executeQuery(query);

            if (rs.next()) {
                rent = rs.getInt("custId");
            }
            return rent;

        } catch (SQLException ex) {
            Logger.getLogger(ClerkForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(ClerkForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ClerkForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 0;
    }

    public int getCost(int id) {
        int rent = 0;

        try {
            Connection conn = new ConnectionHandler().createConnection();
            Statement st = conn.createStatement();

            String query = "select * from Sales where id = " + id;

            ResultSet rs = st.executeQuery(query);

            if (rs.next()) {
                return rs.getInt("totalCost");

            }

        } catch (SQLException ex) {
            Logger.getLogger(ClerkForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(ClerkForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ClerkForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEmployee = new javax.swing.JButton();
        jButtonCust = new javax.swing.JButton();
        jButtonSales = new javax.swing.JButton();
        jButtonEmpData = new javax.swing.JButton();
        jButtonInv = new javax.swing.JButton();
        jButtonReq = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jComboBox = new javax.swing.JComboBox<>();
        jTextCharge = new javax.swing.JTextField();
        jButtonItem = new javax.swing.JButton();
        jTextName = new javax.swing.JTextField();
        jTextPrice = new javax.swing.JTextField();
        jButtonOld = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuLogout = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VRSS [Manager]");

        jButtonEmployee.setText("Add New Employee");
        jButtonEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEmployeeMouseClicked(evt);
            }
        });
        jButtonEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmployeeActionPerformed(evt);
            }
        });

        jButtonCust.setText("View Customer Database");
        jButtonCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustActionPerformed(evt);
            }
        });

        jButtonSales.setText("View Sales Stats");
        jButtonSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalesActionPerformed(evt);
            }
        });

        jButtonEmpData.setText("View Employee Database");
        jButtonEmpData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpDataActionPerformed(evt);
            }
        });

        jButtonInv.setText("View Inventory");
        jButtonInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInvActionPerformed(evt);
            }
        });

        jButtonReq.setText("View New Item Requests");
        jButtonReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReqActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Music", "Video" }));
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });

        jTextCharge.setText("Daily Rental Charge");
        jTextCharge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextChargeMouseClicked(evt);
            }
        });
        jTextCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextChargeActionPerformed(evt);
            }
        });
        jTextCharge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextChargeKeyTyped(evt);
            }
        });

        jButtonItem.setText("Add New Item");
        jButtonItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonItemActionPerformed(evt);
            }
        });

        jTextName.setText("Item Name");
        jTextName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextNameMouseClicked(evt);
            }
        });
        jTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameActionPerformed(evt);
            }
        });

        jTextPrice.setText("Purchase Price");
        jTextPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextPriceMouseClicked(evt);
            }
        });
        jTextPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPriceActionPerformed(evt);
            }
        });
        jTextPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPriceKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextCharge, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jTextName)
                    .addComponent(jTextPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jButtonItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButtonItem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jButtonOld.setText("View Outdated Inventory");
        jButtonOld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOldActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuLogout.setText("Logout");
        jMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuLogout);

        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonEmpData, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCust, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSales, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonInv, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonOld, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonReq, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButtonEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCust, jButtonEmpData, jButtonEmployee, jButtonInv, jButtonOld, jButtonReq, jButtonSales});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonInv, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEmpData, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCust, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonReq, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonOld, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSales, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonCust, jButtonEmpData, jButtonEmployee, jButtonInv, jButtonOld, jButtonReq, jButtonSales});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLogoutActionPerformed
        dispose();
        new VrsForm().setVisible(true);
    }//GEN-LAST:event_jMenuLogoutActionPerformed

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void jButtonEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmployeeActionPerformed
        new AddEmployeeForm().setVisible(true);
    }//GEN-LAST:event_jButtonEmployeeActionPerformed

    private void jTextChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextChargeActionPerformed
        jTextCharge.setText(null);
    }//GEN-LAST:event_jTextChargeActionPerformed

    private void jTextPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPriceActionPerformed
        jTextPrice.setText(null);
    }//GEN-LAST:event_jTextPriceActionPerformed

    private void jButtonItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonItemActionPerformed
        String name = jTextName.getText();
        String type = (String) jComboBox.getSelectedItem();
        int price = -1, charge = -1;
        try {
            charge = Integer.parseInt(jTextCharge.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Daily Rental Charge must be numeric", "Error", JOptionPane.ERROR_MESSAGE);
            jTextCharge.setText(null);
        }
        try {
            price = Integer.parseInt(jTextPrice.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Price must be numeric", "Error", JOptionPane.ERROR_MESSAGE);
            jTextPrice.setText(null);
        }

        if (price != -1 && charge != -1 && !"".equals(name) && !"Item Name".equals(name)) {
            int id = 0;

            String sql = "";
            try {

                Connection conn = new ConnectionHandler().createConnection();
                Statement statement = conn.createStatement();
                String get = "select id from Inventory";
                ResultSet rs = statement.executeQuery(get);

                while (rs.next()) {
                    id = rs.getInt("id");
                }
                id++;
                Calendar calendar = Calendar.getInstance();

                java.sql.Date date1 = new java.sql.Date(Calendar.getInstance().getTime().getTime());
                java.sql.Date date2 = new java.sql.Date(Calendar.getInstance().getTime().getTime());

                //purchaseDate, returnDate,
                String query = "INSERT INTO Inventory (id, name, rent, price, type, purchaseDate, returnDate, loaned) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement st = conn.prepareStatement(query);

                st.setInt(1, id);
                st.setString(2, name);
                st.setInt(3, charge);
                st.setInt(4, price);
                st.setString(5, type);
                st.setDate(6, date1);
                st.setDate(7, date2);
                st.setInt(8, 0);
                st.executeUpdate();
                st.close();

//               
                String update = "update Profit set Expense = Expense + ?";
                st = conn.prepareStatement(update);
                st.setInt(1, price);
                st.executeUpdate();
                st.close();

                JOptionPane.showMessageDialog(null, "Item added with ID: " + id + "!", "Success", JOptionPane.INFORMATION_MESSAGE);

            } catch (SQLException ex) {
                Logger.getLogger(AddEmployeeForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(AddEmployeeForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(AddEmployeeForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Enter all details", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButtonItemActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxActionPerformed

    private void jButtonEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEmployeeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEmployeeMouseClicked

    private void jButtonEmpDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpDataActionPerformed
        new EmployeeDatabaseForm().setVisible(true);
    }//GEN-LAST:event_jButtonEmpDataActionPerformed

    private void jButtonSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalesActionPerformed
        new SalesDataForm().setVisible(true);
        new SalesForm().setVisible(true);
    }//GEN-LAST:event_jButtonSalesActionPerformed

    private void jButtonCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustActionPerformed
        new CustomerDatabaseForm().setVisible(true);
    }//GEN-LAST:event_jButtonCustActionPerformed

    private void jButtonInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInvActionPerformed
        new InventoryForm().setVisible(true);
    }//GEN-LAST:event_jButtonInvActionPerformed

    private void jTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameActionPerformed
        jTextName.setText(null);
    }//GEN-LAST:event_jTextNameActionPerformed

    private void jTextNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextNameMouseClicked
        jTextName.setText(null);
    }//GEN-LAST:event_jTextNameMouseClicked

    private void jTextChargeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextChargeMouseClicked
        jTextCharge.setText(null);
    }//GEN-LAST:event_jTextChargeMouseClicked

    private void jTextPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPriceMouseClicked
        jTextPrice.setText(null);
    }//GEN-LAST:event_jTextPriceMouseClicked

    private void jTextChargeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextChargeKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextChargeKeyTyped

    private void jTextPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPriceKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextPriceKeyTyped

    private void jButtonReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReqActionPerformed
        new RequestsForm().setVisible(true);
    }//GEN-LAST:event_jButtonReqActionPerformed

    private void jButtonOldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOldActionPerformed
        new OutdatedInventoryForm().setVisible(true);
    }//GEN-LAST:event_jButtonOldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCust;
    private javax.swing.JButton jButtonEmpData;
    private javax.swing.JButton jButtonEmployee;
    private javax.swing.JButton jButtonInv;
    private javax.swing.JButton jButtonItem;
    private javax.swing.JButton jButtonOld;
    private javax.swing.JButton jButtonReq;
    private javax.swing.JButton jButtonSales;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenuItem jMenuLogout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextCharge;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextPrice;
    // End of variables declaration//GEN-END:variables
}
